language: python
python:
- 3.6
install:
- pip install -r requirements.txt
script:
- python -m unittest discover
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: EXSEsh5eDQ8w0l4FiEVd0P9KfgFtBrR6KrwShzJMBZ0u8tqsRrey7Exg7xG00GdGGM/9B3nGgwHMx5fv9TwTqJQysDLIoQOGuwVfM6N3IZdyvhkH+IFw7KMYpo2Vu+fsu70keIxmzzGuRyVFBLKauBKMEoci3zS3ubHRynH4BJokYK16j7LePuRz8sHWZeWv8dZWwUnezM6+rp4FN0bQrXpotNvS0cHj5xVh32l0wfD9g2cPL9CQKjPkMC7dB9cIFER52c0Q4YQNPA1T/xD7DW/fWV4A04R/C/Ukegi2JKotvCJDT5g4TcLTixJw6xObPlCFXQEhtMnf661y0Wrjul18jciDrzy7eJgc5XEyrSPLg9CG/B2ma7KYALBXDEWjXl55cT1OCPVd0gDrcNjnbITNGX9JfMfZLQfn6IGk3Q6T77vWOrMPeh89t2eolqyk4OYrTI1twY2qutw1t/UeKLgos11lFAbwQ/GrkWcENexPEW8kabxAnoAaqRPK+AheqVtbKmWkQVSRWl5ps/C5Eq//c6UXQM1fsorcyI5NNMpJHQOz1eBgsvmG9XCiaFbPdI2jOOFIvBvJlDKZ9rIWzhsq4GnxfymGuatKJrCg22RJaczkJWE0YYfLCClBEFtgibY+9lQfdu/HAFRUMQ40akbis5GfqF7uG/HblJ2VApQ=
  app: line-travel-bot
